GET http://localhost:1324/videos?search=mentira

###
POST http://localhost:1324/videos
Content-Type: application/json

{
  "title": "video legal",
  "description": "video legal de verdade",
  "duration": 120
}

###
PUT http://localhost:1324/videos/fd549254-2aaf-4e36-8224-1deec8f119d8
Content-Type: application/json

{
  "title": "video não tão legal assim",
  "description": "video legal de mentira",
  "duration": 120
}

###
DELETE http://localhost:1324/videos/1362fb17-05d0-4648-9307-314ba1f97c01
