GET https://fastify-server-c4sk.onrender.com/videos
# GET https://fastify-server-c4sk.onrender.com/videos?search=mentira

###
POST https://fastify-server-c4sk.onrender.com/videos
Content-Type: application/json

{
  "title": "video legal",
  "description": "video legal de verdade",
  "duration": 120
}

###
PUT https://fastify-server-c4sk.onrender.com/videos/8ed1d930-e99f-41fe-8501-a6487504d3bd
Content-Type: application/json

{
  "title": "video não tão legal assim",
  "description": "video legal de mentira",
  "duration": 120
}

###
DELETE https://fastify-server-c4sk.onrender.com/videos/8ed1d930-e99f-41fe-8501-a6487504d3bd
